on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
      
      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -v -w -y

      - run: |
          xmake package -v -y

      - uses: actions/upload-artifact@v3
        with:
          name: more-events-package-windows-x64-${{ github.sha }}
          path: |
            build/packages/m/more-events/windows/x64/release/

      - uses: actions/upload-artifact@v3
        with:
          name: more-events-plugin-windows-x64-${{ github.sha }}
          path: |
            bin/

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: more-events-package-windows-x64-${{ github.sha }}
          path: release/package/

      - uses: actions/download-artifact@v3
        with:
          name: more-events-plugin-windows-x64-${{ github.sha }}
          path: release/plugin/

      - run: |
          cp COPYING COPYING.LESSER README.md release/plugin/

      - run: |
          zip -r ../../more-events-package-windows-x64.zip *
        working-directory: release/package/

      - run: |
          zip -r ../../more-events-plugin-windows-x64.zip *
        working-directory: release/plugin/

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            more-events-package-windows-x64.zip
            more-events-plugin-windows-x64.zip
