on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -v -w -y

      - run: |
          xmake package -v -y

      - run: |
          Copy-Item bin/* build/packages/m/more-events/windows/x64/release/ -Recurse

      - uses: actions/upload-artifact@v4
        with:
          name: more-events-windows-x64-${{ github.sha }}
          path: |
            build/packages/m/more-events/windows/x64/release/

  update-release-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate release stuff (tooth.json, CHANGELOG.md, etc.)
        run: |
          npm i -g keep-a-changelog
          python scripts/validate_release.py --tag ${{ github.event.release.tag_name }}

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}

            | File | SHA256 |
            | ---- | ------ |

  upload-to-release:
    needs:
      - build
      - update-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: more-events-windows-x64-${{ github.sha }}
          path: artifact

      - run: |
          cp CHANGELOG.md COPYING COPYING.LESSER README.md artifact/

      - run: |
          zip -r ../more-events-windows-x64.zip *
        working-directory: artifact

      - id: calculate-sha256
        run: |
          echo sha256=$(sha256sum more-events-windows-x64.zip | awk '{print $1}') >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v1
        with:
          append_body: true
          body: |
            | more-events-windows-x64.zip | ${{ steps.calculate-sha256.outputs.sha256 }} |
          files: |
            more-events-windows-x64.zip
